### PR TITLE
Add pidgin client documentation

### PR DESCRIPTION
**Pull request by brokenthorn**
Documentation for Pidgin is done. Requesting review.

### CODE REVIEW

**Comment by mwild1** [comment]
Amazing! :smiley: 

One question, did you confirm this in testing?

> If they're using the same server as the currently selected account, you can omit the server name and enter just the user name (only the part on the left of the @ sign).

If yes, I learnt something new about Pidgin :)

**Comment by brokenthorn** [comment]
@mwild1, you are right. The full contact ID might be required always. The server seems to have added `kerry.stafford` to the contacts list when I tried without the part after `@` (and that's how "she" appears in the contacts list, without a server name) but since I already have a `kerry.stafford@superxmpp.com` in my buddy list, I expected an error message which I didn't get. I left the contact in the list so maybe you can investigate more on the server side if it's at all important. I also pushed another commit to this branch to fix this.

image

**Comment by brokenthorn** [comment]
I see you've merged the commit... sorry. Will you revert it or should I and make a new PR?

**Comment by mwild1** [comment]
Just make a new PR or commit directly is fine :)

**Pull request merged**
